single(136-lyrics-coldplay,512).
single(42-lyrics-coldplay,387).
single(amsterdam-dvd-lyrics-coldplay,577).
single(amsterdam-lyrics-coldplay,573).
single(animals-lyrics-coldplay,480).
single(bigger-stronger-lyrics-coldplay,391).
single(brothers-and-sisters-lyrics-coldplay,464).
single(careful-where-you-stand-lyrics-coldplay,444).
single(cemeteries-of-london-lyrics-coldplay,554).
single(charlie-brown-lyrics-coldplay,521).
single(christmas-lights-lyrics-coldplay,658).
single(clocks-edit-lyrics-coldplay,557).
single(clocks-live-lyrics-coldplay,552).
single(clocks-lyrics-coldplay,547).
single(crests-of-waves-lyrics-coldplay,580).
single(daylight-dvd-lyrics-coldplay,457).
single(daylight-lyrics-coldplay,442).
single(death-and-all-his-friends-lyrics-coldplay,419).
single(dont-let-it-break-your-heart-lyrics-coldplay,496).
single(dont-panic-lyrics-coldplay,361).
single(easy-to-please-lyrics-coldplay,296).
single(escapist-lyrics-coldplay,235).
single(every-teardrop-is-a-waterfall-lyrics-coldplay,706).
single(everythings-not-lost-lyrics-coldplay,480).
single(fix-you-dvd-lyrics-coldplay,510).
single(fix-you-edit-lyrics-coldplay,511).
single(fix-you-lyrics-coldplay,507).
single(fix-you-multimedia-track-lyrics-coldplay,519).
single(for-you-lyrics-coldplay,374).
single(glass-of-water-lyrics-coldplay,611).
single(god-put-a-smile-upon-your-face-dvd-lyrics-coldplay,489).
single(god-put-a-smile-upon-your-face-lyrics-coldplay,486).
single(gravity-audiomultimedia-track-lyrics-coldplay,458).
single(gravity-lyrics-coldplay,446).
single(green-eyes-lyrics-coldplay,481).
single(hardest-part-lyrics-coldplay,517).
single(help-is-round-the-corner-lyrics-coldplay,451).
single(high-speed-lyrics-coldplay,316).
single(hopeful-transmission-lyrics-coldplay,211).
single(how-you-see-the-world-live-from-earls-court-lyrics-coldplay,615).
single(hurts-like-heaven-lyrics-coldplay,702).
single(i-ran-away-lyrics-coldplay,548).
single(in-my-place-dvd-lyrics-coldplay,455).
single(in-my-place-live-lyrics-coldplay,460).
single(in-my-place-lyrics-coldplay,451).
single(in-my-place-multimedia-track-lyrics-coldplay,463).
single(life-in-technicolor-ii-lyrics-coldplay,520).
single(life-in-technicolor-lyrics-coldplay,211).
single(life-in-technicolor-pt-2-lyrics-coldplay,531).
single(life-is-for-living-dvd-lyrics-coldplay,401).
single(lips-like-sugar-lyrics-coldplay,505).
single(lost-lyrics-coldplay,465).
single(lost-with-jay-z-lyrics-coldplay,837).
single(lovers-in-japan-osaka-sun-mix-lyrics-coldplay,602).
single(lovers-in-japanreign-of-love-lyrics-coldplay,588).
single(low-lyrics-coldplay,586).
single(major-minus-lyrics-coldplay,513).
single(message-lyrics-coldplay,507).
single(mmix-lyrics-coldplay,196).
single(moses-lyrics-coldplay,537).
single(murder-lyrics-coldplay,364).
single(mylo-xyloto-lyrics-coldplay,204).
single(no-more-keeping-my-feet-on-the-ground-lyrics-coldplay,541).
single(no-more-keeping-my-feet-on-the-ground-taken-from-the-safety-ep-lyrics-coldplay,556).
single(now-my-feet-wont-touch-the-ground-lyrics-coldplay,372).
single(one-i-love-dvd-lyrics-coldplay,267).
single(one-i-love-lyrics-coldplay,262).
single(only-superstition-lyrics-coldplay,546).
single(parachutes-lyrics-coldplay,272).
single(paradise-lyrics-coldplay,545).
single(politik-dvd-lyrics-coldplay,471).
single(politik-lyrics-coldplay,467).
single(postcards-from-far-away-lyrics-coldplay,214).
single(pour-me-live-at-the-hollywood-bowl-lyrics-coldplay,399).
single(princess-of-china-lyrics-coldplay,544).
single(proof-audiomultimedia-track-lyrics-coldplay,386).
single(proof-lyrics-coldplay,370).
single(prospekts-marchpoppyfields-lyrics-coldplay,546).
single(rainy-day-lyrics-coldplay,588).
single(rush-of-blood-to-the-head-lyrics-coldplay,750).
single(scientist-dvd-lyrics-coldplay,587).
single(scientist-lyrics-coldplay,575).
single(see-you-soon-lyrics-coldplay,404).
single(shiver-lyrics-coldplay,583).
single(sleeping-sun-audiomultimedia-track-lyrics-coldplay,501).
single(sparks-lyrics-coldplay,400).
single(speed-of-sound-dvd-lyrics-coldplay,775).
single(speed-of-sound-lyrics-coldplay,772).
single(speed-of-sound-multimedia-track-lyrics-coldplay,782).
single(spies-lyrics-coldplay,573).
single(square-one-lyrics-coldplay,634).
single(strawberry-swing-lyrics-coldplay,514).
single(such-a-rush-lyrics-coldplay,419).
single(swallowed-in-the-sea-lyrics-coldplay,660).
single(talk-album-version-lyrics-coldplay,647).
single(talk-lyrics-coldplay,636).
single(talk-multimedia-track-lyrics-coldplay,648).
single(the-scientist-lyrics-coldplay,589).
single(things-i-dont-understand-audiomultimedia-track-lyrics-coldplay,531).
single(things-i-dont-understand-lyrics-coldplay,518).
single(til-kingdom-come-hidden-track-lyrics-coldplay,566).
single(til-kingdom-come-lyrics-coldplay,559).
single(trouble-dvd-lyrics-coldplay,450).
single(trouble-lyrics-coldplay,446).
single(twisted-logic-lyrics-coldplay,507).
single(ufo-lyrics-coldplay,405).
single(up-in-flames-lyrics-coldplay,352).
single(up-with-the-birds-lyrics-coldplay,561).
single(us-against-the-world-lyrics-coldplay,638).
single(user,123).
single(violet-hill-lyrics-coldplay,636).
single(viva-la-vida-full-album-version-lyrics-coldplay,785).
single(viva-la-vida-lyrics-coldplay,768).
single(viva-la-vida-radio-edit-lyrics-coldplay,791).
single(warning-sign-lyrics-coldplay,466).
single(we-never-change-lyrics-coldplay,416).
single(what-if-lyrics-coldplay,484).
single(whisper-lyrics-coldplay,425).
single(white-shadow-lyrics-coldplay,663).
single(white-shadows-lyrics-coldplay,656).
single(world-turned-upside-down-audiomultimedia-track-lyrics-coldplay,707).
single(world-turned-upside-down-lyrics-coldplay,693).
single(xy-lyrics-coldplay,444).
single(yellow-acoustic-version-from-jo-whileys-lunchtime-social-lyrics-coldplay,513).
single(yellow-live-lyrics-coldplay,482).
single(yellow-lyrics-coldplay,480).
single(yes-lyrics-coldplay,560).
single(you-only-live-twice-live-from-norway-lyrics-coldplay,397).
single(you-only-live-twice-lyrics-coldplay,392).
